from __future__ import annotations

from typing import Protocol

from telize.config.models import Step
from telize.runtime.state import StepResult


class WorkflowObserver(Protocol):
    """Receive lifecycle events while a workflow executes."""

    def on_workflow_start(self, entrypoint: str, *, estimated_steps: int) -> None: ...

    def on_flow_start(self, flow_name: str) -> None: ...

    def on_flow_complete(self, flow_name: str) -> None: ...

    def on_step_start(self, flow_name: str, step: Step, *, index: int) -> None: ...

    def on_step_complete(self, flow_name: str, step: Step, result: StepResult) -> None: ...

    def on_step_error(self, flow_name: str, step: Step, error: BaseException) -> None: ...

    def on_workflow_complete(self) -> None: ...


class NullObserver:
    """No-op observer for runs without a UI."""

    def on_workflow_start(self, entrypoint: str, *, estimated_steps: int) -> None: ...

    def on_flow_start(self, flow_name: str) -> None: ...

    def on_flow_complete(self, flow_name: str) -> None: ...

    def on_step_start(self, flow_name: str, step: Step, *, index: int) -> None: ...

    def on_step_complete(self, flow_name: str, step: Step, result: StepResult) -> None: ...

    def on_step_error(self, flow_name: str, step: Step, error: BaseException) -> None: ...

    def on_workflow_complete(self) -> None: ...
